In [1]:
import pandas as pd
import numpy as np
index = pd.date_range('1/1/2000',periods=8)
s = pd.Series(np.random.randn(5),index=list('abcde'))
df = pd.DataFrame(np.random.randn(8,3),index=index,columns=list('ABC'))

In [2]:
# head and tail
long_series = pd.Series(np.random.randn(1000))
long_series.head()

0    1.695357
1    0.205421
2   -0.072011
3   -1.276270
4    0.568372
dtype: float64

In [3]:
long_series.tail()

995   -0.351200
996    0.308487
997   -0.507881
998    1.418813
999   -0.679333
dtype: float64

In [4]:
# attributes and underlying data
df[:2]

A         B         C
2000-01-01 -1.095817  0.259232 -0.439481
2000-01-02 -1.904658  0.693948 -0.323508

In [6]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2000-01-01 -1.095817  0.259232 -0.439481
2000-01-02 -1.904658  0.693948 -0.323508
2000-01-03 -2.316071  1.041846  0.044508
2000-01-04  1.008616 -0.209073  0.105226
2000-01-05  0.358168  1.047441 -0.494760
2000-01-06  0.362876 -0.047068 -0.102722
2000-01-07  0.820029  0.717706 -0.057458
2000-01-08 -0.939636 -0.772419  1.458485

In [7]:
s.array

<PandasArray>
[  0.1923072659694022, -0.13181860540312237,  0.27170413643340535,
  0.09289662082208537,  0.24693894606561712]
Length: 5, dtype: float64

In [8]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [9]:
s.to_numpy()

array([ 0.19230727, -0.13181861,  0.27170414,  0.09289662,  0.24693895])

In [10]:
np.asarray(s)

array([ 0.19230727, -0.13181861,  0.27170414,  0.09289662,  0.24693895])

In [11]:
ser = pd.Series(pd.date_range('2000',periods=2,tz='CET'))
ser

0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]

In [12]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [13]:
ser.to_numpy(dtype='datetime64[ns]')

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [14]:
df.to_numpy()

array([[-1.09581702,  0.25923166, -0.4394812 ],
       [-1.90465767,  0.69394752, -0.32350787],
       [-2.31607058,  1.04184603,  0.04450828],
       [ 1.00861594, -0.20907253,  0.10522558],
       [ 0.35816815,  1.04744064, -0.4947603 ],
       [ 0.36287593, -0.04706848, -0.1027225 ],
       [ 0.82002873,  0.71770621, -0.057458  ],
       [-0.93963578, -0.77241933,  1.45848458]])

In [19]:
# accelerated operations
# install numexpr and bottleneck libraries

In [20]:
pd.get_option('compute.use_bottleneck')

True

In [21]:
pd.get_option('compute.use_numexpr')

True

In [23]:
df = pd.DataFrame(
     {
         "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
         "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
         "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
     }
 )
df

one       two     three
a -0.651103  0.104644       NaN
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [24]:
row = df.iloc[1]

In [25]:
column = df['two']
df.sub(row,axis='columns')

one       two     three
a -2.377132  0.340969       NaN
b  0.000000  0.000000  0.000000
c -0.963196 -1.958817 -3.534591
d       NaN  0.925823 -0.403609

In [26]:
df.sub(row,axis=1)

one       two     three
a -2.377132  0.340969       NaN
b  0.000000  0.000000  0.000000
c -0.963196 -1.958817 -3.534591
d       NaN  0.925823 -0.403609

In [27]:
df.sub(column,axis='index')

one  two     three
a -0.755746  0.0       NaN
b  1.962355  0.0  1.656057
c  2.957976  0.0  0.080283
d       NaN  0.0  0.326626

In [28]:
df.sub(column,axis=0)

one  two     three
a -0.755746  0.0       NaN
b  1.962355  0.0  1.656057
c  2.957976  0.0  0.080283
d       NaN  0.0  0.326626

In [29]:
dfmi = df.copy()
dfmi.index = pd.MultiIndex.from_tuples([(1,'a'),(1,'b'),(1,'c'),(2,'a')],names=['first','second'])
dfmi.sub(column,axis=0,level='second')

one       two     three
first second                              
1     a      -0.755746  0.000000       NaN
      b       1.962355  0.000000  1.656057
      c       2.957976  0.000000  0.080283
2     a            NaN  0.584854  0.911480

In [30]:
dfmi

one       two     three
first second                              
1     a      -0.651103  0.104644       NaN
      b       1.726030 -0.236325  1.419732
      c       0.762834 -2.195142 -2.114859
2     a            NaN  0.689498  1.016124

In [31]:
s = pd.Series(np.arange(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [32]:
div,rem = divmod(s,3)

In [33]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int64

In [34]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int64

In [36]:
idx = pd.Index(np.arange(10))
div,rem = divmod(idx,3)

In [37]:
div

Int64Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [42]:
df2 = df.copy()

In [49]:
df

one       two     three
a -0.651103  0.104644       NaN
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [47]:
df2.iloc[0,2] = 1

In [48]:
df2

one       two     three
a -0.651103  0.104644  1.000000
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [50]:
df+df2

one       two     three
a -1.302205  0.209287       NaN
b  3.452060 -0.472650  2.839464
c  1.525668 -4.390285 -4.229718
d       NaN  1.378996  2.032247

In [51]:
df.add(df2,fill_value=0)

one       two     three
a -1.302205  0.209287  1.000000
b  3.452060 -0.472650  2.839464
c  1.525668 -4.390285 -4.229718
d       NaN  1.378996  2.032247

In [53]:
# flexible comparisons
# eq,ne,lt,gt,le,ge
df.ne(df2)

one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

In [54]:
# boolean reductions
# enpty any() all() bool()
(df>0).all()

one      False
two      False
three    False
dtype: bool

In [55]:
(df>0).any()

one      True
two      True
three    True
dtype: bool

In [56]:
(df>0).any().any()

True

In [57]:
df.empty

False

In [58]:
pd.DataFrame(columns=list('ABC')).empty

True

In [59]:
pd.Series([True]).bool()

True

In [60]:
pd.DataFrame([[True]]).bool()

True

In [61]:
df + df == df *2

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [62]:
(df+df==df*2).all()

one      False
two       True
three    False
dtype: bool

In [63]:
(df + df).equals(df *2)

True

In [67]:
df1 = pd.DataFrame({'col':['foo',0,np.nan]})
df2 = pd.DataFrame({'col':[np.nan,0,'foo']},index=[2,1,0])
df1.equals(df2)

False

In [68]:
df1.equals(df2.sort_index())

True

In [69]:
pd.Series(["foo", "bar", "baz"]) == "foo"

0     True
1    False
2    False
dtype: bool

In [70]:
pd.Series(["foo", "bar", "baz"]) == pd.Index(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

In [71]:
pd.Series(["foo", "bar", "baz"]) == np.array(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

In [72]:
pd.Series(['foo', 'bar', 'baz']) == pd.Series(['foo', 'bar'])

ValueError: Can only compare identically-labeled Series objects

In [73]:
np.array([1, 2, 3]) == np.array([2])

array([False,  True, False])

In [74]:
np.array([1, 2, 3]) == np.array([1, 2])

/var/folders/g6/h24w2cnn0bzbzz1dc4v4fplm0000gn/T/ipykernel_7725/1336612208.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.array([1, 2, 3]) == np.array([1, 2])


False

In [75]:
df1 = pd.DataFrame(
     {"A": [1.0, np.nan, 3.0, 5.0, np.nan], "B": [np.nan, 2.0, 3.0, np.nan, 6.0]}
 )
df2 = pd.DataFrame(
     {
         "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
         "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],
     }
 )

In [76]:
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [77]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [78]:
df1.combine_first(df2)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [79]:
def combiner(x,y):
    return np.where(pd.isna(x),y,x)
df1.combine(df2,combiner)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [80]:
# descriptive statistics
# sum() mean() quantile() cumsum() cumprod()
# axis: 'index'(axis=0,default) 'columns'(axis=1)
df

one       two     three
a -0.651103  0.104644       NaN
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [81]:
df.mean(0)

one      0.612587
two     -0.409331
three    0.106999
dtype: float64

In [82]:
df.mean(1)

a   -0.273229
b    0.969812
c   -1.182389
d    0.852811
dtype: float64

In [83]:
df.sum(0,skipna=False)

one           NaN
two     -1.637326
three         NaN
dtype: float64

In [84]:
df.sum(1,skipna=True)

a   -0.546459
b    2.909437
c   -3.547167
d    1.705621
dtype: float64

In [85]:
# standardization (rendering data zero mean and standard deviation of 1)
ts_stand = (df - df.mean()) / df.std()
ts_stand

one       two     three
a -1.056891  0.411042       NaN
b  0.931231  0.138359  0.678507
c  0.125659 -1.428169 -1.148402
d       NaN  0.878768  0.469895

In [89]:
ts_stand.mean(0)

one      7.401487e-17
two      5.551115e-17
three    1.850372e-17
dtype: float64

In [90]:
ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [93]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)  
xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [95]:
summary = pd.DataFrame(dict(
    Function = ['count', 'sum', 'mean', 'mad', 'median', 'min', 'max', 'mode', 'abs', 'prod', 'std', 'var', 'sem', 'skew', 'kurt', 'quantile', 'cumsum', 'cumprod', 'cummax', 'cummin'],
    Description = ['Number of non-NA observations', 'Sum of values', 'Mean of values', 'Mean absolute deviation', 'Arithmetic median of values', 'Minimum', 'Maximum', 'Mode', 'Absolute Value', 'Product of values', 'Bessel-corrected sample standard deviation', 'Unbiased variance', 'Standard error of the mean', 'Sample skewness (3rd moment)', 'Sample kurtosis (4th moment)', 'Sample quantile (value at %)', 'Cumulative sum', 'Cumulative product', 'Cumulative maximum', 'Cumulative minimum']
))
summary

Function                                 Description
0      count               Number of non-NA observations
1        sum                               Sum of values
2       mean                              Mean of values
3        mad                     Mean absolute deviation
4     median                 Arithmetic median of values
5        min                                     Minimum
6        max                                     Maximum
7       mode                                        Mode
8        abs                              Absolute Value
9       prod                           Product of values
10       std  Bessel-corrected sample standard deviation
11       var                           Unbiased variance
12       sem                  Standard error of the mean
13      skew                Sample skewness (3rd moment)
14      kurt                Sample kurtosis (4th moment)
15  quantile                Sample quantile (value at %)
16    cumsum                              Cumulative sum
17   cumprod                          Cumulative product
18    cummax                          Cumulative maximum
19    cummin                          Cumulative minimum

In [96]:
summary.T

0   ...                  19
Function                             count  ...              cummin
Description  Number of non-NA observations  ...  Cumulative minimum

[2 rows x 20 columns]

In [97]:
summary = summary.T
summary.columns = summary.iloc[0]

Function                             count  ...              cummin
Function                             count  ...              cummin
Description  Number of non-NA observations  ...  Cumulative minimum

[2 rows x 20 columns]

In [100]:
summary

Function                             count  ...              cummin
Function                             count  ...              cummin
Description  Number of non-NA observations  ...  Cumulative minimum

[2 rows x 20 columns]

In [101]:
summary['count']

Function                               count
Description    Number of non-NA observations
Name: count, dtype: object

In [102]:
df

one       two     three
a -0.651103  0.104644       NaN
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [103]:
df.cumsum()

one       two     three
a -0.651103  0.104644       NaN
b  1.074927 -0.131681  1.419732
c  1.837761 -2.326824 -0.695127
d       NaN -1.637326  0.320997

In [104]:
df.cumsum(axis=1)

one       two     three
a -0.651103 -0.546459       NaN
b  1.726030  1.489705  2.909437
c  0.762834 -1.432308 -3.547167
d       NaN  0.689498  1.705621

In [105]:
df.cumprod()

one       two     three
a -0.651103  0.104644       NaN
b -1.123822 -0.024730  1.419732
c -0.857290  0.054286 -3.002533
d       NaN  0.037430 -3.050945

In [106]:
series = pd.Series(np.random.randn(500))
series[20:500] = np.nan
series[10:20] = 5
series.nunique()

11

In [107]:
series = pd.Series(np.random.randn(1000))
series[::2] = np.nan
series.describe()

count    500.000000
mean      -0.025612
std        0.983763
min       -3.005927
25%       -0.636834
50%       -0.085996
75%        0.636807
max        3.120627
dtype: float64

In [108]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=["a", "b", "c", "d", "e"])
frame.iloc[::2] = np.nan
frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean    -0.028430   -0.051022   -0.064837    0.078759    0.007629
std      0.997033    0.974701    1.017545    0.998150    1.023021
min     -3.113441   -2.633296   -3.416213   -2.765497   -3.032366
25%     -0.751089   -0.705241   -0.766361   -0.593078   -0.627554
50%     -0.007769   -0.009185   -0.018122    0.060225    0.077480
75%      0.648952    0.590748    0.604950    0.791860    0.706319
max      3.046852    2.794748    4.583092    2.756118    3.159980

In [109]:
series.describe(percentiles=[0.05,0.25,0.75,0.95])

count    500.000000
mean      -0.025612
std        0.983763
min       -3.005927
5%        -1.630507
25%       -0.636834
50%       -0.085996
75%        0.636807
95%        1.576707
max        3.120627
dtype: float64

In [110]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [111]:
frame = pd.DataFrame({"a": ["Yes", "Yes", "No", "No"], "b": range(4)})
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [112]:
frame.describe(include=['object'])

a
count    4
unique   2
top     No
freq     2

In [113]:
frame.describe(include=['number'])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [116]:
frame.describe(include='all')

a         b
count     4  4.000000
unique    2       NaN
top      No       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

In [117]:
# index of min/max values
s1 = pd.Series(np.random.randn(5))
s1

0    0.153039
1   -0.690630
2   -0.699177
3    1.040353
4   -0.540299
dtype: float64

In [120]:
s1.idxmin(),s1.idxmax()

(2, 3)

In [122]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])
df1

A         B         C
0 -0.881172  0.250761 -1.791470
1 -0.460997  0.158301  0.810249
2 -0.029616  2.294375  0.084524
3 -0.102333 -0.016234  1.376132
4  0.126782  0.212862 -0.357839

In [124]:
df1.idxmin(axis=0),df1.idxmax(axis=1)

(A    0
 B    3
 C    0
 dtype: int64,
 0    B
 1    C
 2    B
 3    C
 4    B
 dtype: object)

In [126]:
data = np.random.randint(0,7,size=50)
s = pd.Series(data)
data

array([2, 3, 4, 2, 6, 6, 3, 1, 2, 3, 0, 3, 3, 6, 0, 6, 1, 5, 1, 0, 1, 0,
       5, 6, 1, 6, 3, 0, 5, 4, 1, 3, 2, 3, 6, 3, 3, 2, 5, 5, 5, 2, 6, 0,
       3, 4, 6, 2, 0, 5])

In [127]:
s.value_counts()

3    11
6     9
0     7
2     7
5     7
1     6
4     3
dtype: int64

In [128]:
pd.value_counts(data)

3    11
6     9
0     7
2     7
5     7
1     6
4     3
dtype: int64

In [129]:
data = {"a": [1, 2, 3, 4], "b": ["x", "x", "y", "y"]}
frame = pd.DataFrame(data)
frame.value_counts()

a  b
1  x    1
2  x    1
3  y    1
4  y    1
dtype: int64

In [132]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7,7])
s5.mode()

0    3
1    7
dtype: int64

In [137]:
df5 = pd.DataFrame(
     {
         "A": np.random.randint(0, 7, size=50),
         "B": np.random.randint(-10, 15, size=50),
     }
 )
df5.mode()

A  B
0  4.0 -8
1  NaN -6
2  NaN -5
3  NaN  8

In [138]:
# discretization and quantiling
arr = np.random.randn(20)
factor = pd.cut(arr,4)
factor

[(-1.965, -0.842], (0.277, 1.397], (-0.842, 0.277], (-0.842, 0.277], (-0.842, 0.277], ..., (1.397, 2.516], (-0.842, 0.277], (-0.842, 0.277], (-0.842, 0.277], (0.277, 1.397]]
Length: 20
Categories (4, interval[float64]): [(-1.965, -0.842] < (-0.842, 0.277] < (0.277, 1.397] < (1.397, 2.516]]

In [140]:
factor = pd.cut(arr,[-5,-1,0,1,5])
factor

[(-5, -1], (1, 5], (-1, 0], (-1, 0], (-1, 0], ..., (1, 5], (0, 1], (-1, 0], (-1, 0], (0, 1]]
Length: 20
Categories (4, interval[int64]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [141]:
arr = np.random.randn(30)
factor = pd.qcut(arr,[0,0.25,0.5,0.75,1])
factor

[(0.277, 0.829], (-0.363, 0.277], (-2.807, -0.363], (-0.363, 0.277], (0.829, 2.248], ..., (0.277, 0.829], (-2.807, -0.363], (0.829, 2.248], (0.277, 0.829], (-0.363, 0.277]]
Length: 30
Categories (4, interval[float64]): [(-2.807, -0.363] < (-0.363, 0.277] < (0.277, 0.829] < (0.829, 2.248]]

In [142]:
pd.value_counts(factor)

(-2.807, -0.363]    8
(0.829, 2.248]      8
(-0.363, 0.277]     7
(0.277, 0.829]      7
dtype: int64

In [144]:
arr = np.random.randn(20)
factor = pd.cut(arr,[-np.inf,0,np.inf])
factor

[(0.0, inf], (0.0, inf], (-inf, 0.0], (0.0, inf], (-inf, 0.0], ..., (0.0, inf], (0.0, inf], (0.0, inf], (-inf, 0.0], (0.0, inf]]
Length: 20
Categories (2, interval[float64]): [(-inf, 0.0] < (0.0, inf]]

In [145]:
factor.value_counts()

(-inf, 0.0]    10
(0.0, inf]     10
dtype: int64

In [146]:
# function application
# pipe() apply() agg() transform() applymap()

In [148]:
# Tablewise function application
def extract_city_name(df):
    df['city_name'] = df['city_and_code'].str.split(',').str.get(0)
    return df

In [150]:
def add_country_name(df,country_name=None):
    col = 'city_name'
    df['city_and_country'] = df[col] + country_name
    return df

In [151]:
df_p = pd.DataFrame({"city_and_code": ["Chicago, IL"]})

In [152]:
add_country_name(extract_city_name(df_p),country_name='US')

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

In [154]:
df_p.pipe(extract_city_name).pipe(add_country_name,country_name='US')

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

In [155]:
def add_country_name(country_name,df):
    col = 'city_name'
    df['city_and_country'] = df[col] + country_name
    return df

In [156]:
df_p.pipe(extract_city_name).pipe((add_country_name,'df'),country_name='US')

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

In [157]:
# Row or column-wise function application
df.apply(np.mean)

one      0.612587
two     -0.409331
three    0.106999
dtype: float64

In [158]:
df.apply(np.mean,axis=1)

a   -0.273229
b    0.969812
c   -1.182389
d    0.852811
dtype: float64

In [159]:
df.apply(lambda x:x.max()-x.min())

one      2.377132
two      2.884640
three    3.534591
dtype: float64

In [160]:
df

one       two     three
a -0.651103  0.104644       NaN
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [161]:
df.apply(np.cumsum)

one       two     three
a -0.651103  0.104644       NaN
b  1.074927 -0.131681  1.419732
c  1.837761 -2.326824 -0.695127
d       NaN -1.637326  0.320997

In [162]:
df.apply('mean')

one      0.612587
two     -0.409331
three    0.106999
dtype: float64

In [163]:
def subtract_and_divide(x, sub, divide=1):
    return (x - sub) / divide
df.apply(subtract_and_divide,args=(5,),divide=3)

one       two     three
a -1.883701 -1.631785       NaN
b -1.091323 -1.745442 -1.193423
c -1.412389 -2.398381 -2.371620
d       NaN -1.436834 -1.327959

In [168]:
tsdf = pd.DataFrame(
     np.random.randn(1000, 3),
     columns=["A", "B", "C"],
     index=pd.date_range("1/1/2000", periods=1000),
 )

In [170]:
tsdf.apply(lambda x: x.idxmax())

A   2001-08-19
B   2001-01-20
C   2002-08-31
dtype: datetime64[ns]

In [173]:
tsdf = tsdf[0:20]
tsdf

A         B         C
2000-01-01 -0.209298  0.314519 -0.828020
2000-01-02 -1.572457 -0.315091  1.607668
2000-01-03 -0.979171 -0.902697  0.862345
2000-01-04 -0.304167  0.893110 -1.217016
2000-01-05 -1.446276  1.201281 -1.709263
2000-01-06 -0.656149 -0.187835 -1.004965
2000-01-07 -0.871906 -0.147783 -0.688861
2000-01-08  0.938781 -1.231138  0.955368
2000-01-09 -0.557834  1.851660  2.084460
2000-01-10  0.488692  0.196150 -1.259979
2000-01-11 -0.249123  0.828278 -0.951598
2000-01-12 -0.760426 -0.492169  0.438989
2000-01-13 -0.341845  0.662541 -0.285030
2000-01-14 -0.848799  0.155119  1.615333
2000-01-15  1.495441 -0.114788 -0.552733
2000-01-16 -0.787456 -2.229133 -1.380931
2000-01-17 -1.177824  0.576469  0.169875
2000-01-18 -1.956151 -1.239143  0.041240
2000-01-19  2.033538  0.213685 -0.147879
2000-01-20 -0.726380 -0.593052 -1.174480

In [174]:
tsdf[10:15] = np.nan

In [176]:
tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01 -0.209298  0.314519 -0.828020
2000-01-02 -1.572457 -0.315091  1.607668
2000-01-03 -0.979171 -0.902697  0.862345
2000-01-04 -0.304167  0.893110 -1.217016
2000-01-05 -1.446276  1.201281 -1.709263
2000-01-06 -0.656149 -0.187835 -1.004965
2000-01-07 -0.871906 -0.147783 -0.688861
2000-01-08  0.938781 -1.231138  0.955368
2000-01-09 -0.557834  1.851660  2.084460
2000-01-10  0.488692  0.196150 -1.259979
2000-01-11  0.276000 -0.208064 -1.280138
2000-01-12  0.063309 -0.612278 -1.300296
2000-01-13 -0.149382 -1.016491 -1.320455
2000-01-14 -0.362073 -1.420705 -1.340614
2000-01-15 -0.574765 -1.824919 -1.360772
2000-01-16 -0.787456 -2.229133 -1.380931
2000-01-17 -1.177824  0.576469  0.169875
2000-01-18 -1.956151 -1.239143  0.041240
2000-01-19  2.033538  0.213685 -0.147879
2000-01-20 -0.726380 -0.593052 -1.174480

In [177]:
# aggregation api
tsdf = pd.DataFrame(np.random.randn(10,3),columns=list('ABC'),index=pd.date_range('1/1/2000',periods=10))

In [178]:
tsdf.iloc[3:7]=np.nan
tsdf

A         B         C
2000-01-01  0.660533  0.141087 -1.052558
2000-01-02  0.886134  0.532946 -0.266650
2000-01-03 -0.569746  1.330600  0.359502
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.069802  0.252220  1.083946
2000-01-09  1.847431 -0.033768  1.058153
2000-01-10 -1.219176  0.792724  0.784100

In [179]:
tsdf.agg(np.sum)

A    1.674979
B    3.015809
C    1.966494
dtype: float64

In [180]:
tsdf.agg('sum')

A    1.674979
B    3.015809
C    1.966494
dtype: float64

In [181]:
tsdf.sum()

A    1.674979
B    3.015809
C    1.966494
dtype: float64

In [182]:
tsdf['A'].agg('sum')

1.6749786746373314

In [183]:
tsdf.agg(['sum'])

A         B         C
sum  1.674979  3.015809  1.966494

In [185]:
tsdf.agg(['sum','mean'])

A         B         C
sum   1.674979  3.015809  1.966494
mean  0.279163  0.502635  0.327749

In [186]:
tsdf['A'].agg(['sum','mean'])

sum     1.674979
mean    0.279163
Name: A, dtype: float64

In [193]:
tsdf['A'].agg(['sum','mean']).index

Index(['sum', 'mean'], dtype='object')

In [194]:
tsdf.agg({"A": "mean", "B": "sum"})

A    0.279163
B    3.015809
dtype: float64

In [195]:
tsdf.agg({"A": ["mean", "min"], "B": "sum"})

A         B
mean  0.279163       NaN
min  -1.219176       NaN
sum        NaN  3.015809

In [196]:
mdf = pd.DataFrame(
     {
         "A": [1, 2, 3],
         "B": [1.0, 2.0, 3.0],
         "C": ["foo", "bar", "baz"],
         "D": pd.date_range("20130101", periods=3),
     }
 )
mdf.dtypes

A             int64
B           float64
C            object
D    datetime64[ns]
dtype: object

In [197]:
mdf.agg(['min','sum'])

A    B          C          D
min  1  1.0        bar 2013-01-01
sum  6  6.0  foobarbaz        NaT

In [198]:
tsdf.apply(pd.Series.quantile,q=0.25)

A   -0.409859
B    0.168870
C   -0.110112
dtype: float64

In [200]:
from functools import partial
q_25 = partial(pd.Series.quantile,q=0.25)
q_25.__name__='25%'
q_75 = partial(pd.Series.quantile,q=0.75)
q_75.__name__='75%'
tsdf.agg(["count", "mean", "std", "min", q_25, "median", q_75, "max"])

A         B         C
count   6.000000  6.000000  6.000000
mean    0.279163  0.502635  0.327749
std     1.093876  0.500350  0.845357
min    -1.219176 -0.033768 -1.052558
25%    -0.409859  0.168870 -0.110112
median  0.365168  0.392583  0.571801
75%     0.829734  0.727779  0.989640
max     1.847431  1.330600  1.083946

In [201]:
# transform api
tsdf.transform(np.abs)

A         B         C
2000-01-01  0.660533  0.141087  1.052558
2000-01-02  0.886134  0.532946  0.266650
2000-01-03  0.569746  1.330600  0.359502
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.069802  0.252220  1.083946
2000-01-09  1.847431  0.033768  1.058153
2000-01-10  1.219176  0.792724  0.784100

In [202]:
tsdf.agg(np.abs)

A         B         C
2000-01-01  0.660533  0.141087  1.052558
2000-01-02  0.886134  0.532946  0.266650
2000-01-03  0.569746  1.330600  0.359502
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.069802  0.252220  1.083946
2000-01-09  1.847431  0.033768  1.058153
2000-01-10  1.219176  0.792724  0.784100

In [203]:
tsdf.transform([np.abs, lambda x: x + 1])

A                   B                   C          
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  0.660533  1.660533  0.141087  1.141087  1.052558 -0.052558
2000-01-02  0.886134  1.886134  0.532946  1.532946  0.266650  0.733350
2000-01-03  0.569746  0.430254  1.330600  2.330600  0.359502  1.359502
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  0.069802  1.069802  0.252220  1.252220  1.083946  2.083946
2000-01-09  1.847431  2.847431  0.033768  0.966232  1.058153  2.058153
2000-01-10  1.219176 -0.219176  0.792724  1.792724  0.784100  1.784100

In [204]:
tsdf.agg([np.abs, lambda x: x + 1])

A                   B                   C          
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  0.660533  1.660533  0.141087  1.141087  1.052558 -0.052558
2000-01-02  0.886134  1.886134  0.532946  1.532946  0.266650  0.733350
2000-01-03  0.569746  0.430254  1.330600  2.330600  0.359502  1.359502
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  0.069802  1.069802  0.252220  1.252220  1.083946  2.083946
2000-01-09  1.847431  2.847431  0.033768  0.966232  1.058153  2.058153
2000-01-10  1.219176 -0.219176  0.792724  1.792724  0.784100  1.784100

In [206]:
df4 = df

In [207]:
def f(x):
    return len(str(x))
df4['one'].map(f)

a    19
b    17
c    18
d     3
Name: one, dtype: int64

In [208]:
df4.applymap(f)

one  two  three
a   19   19      3
b   17   20     18
c   18   18     19
d    3   18     18

In [238]:
s = pd.Series(
     ["six", "seven", "six", "seven", "six"], index=["a", "b", "c", "d", "e"] )
t = pd.Series({"six": 6.0, "seven": 7.0})
t

six      6.0
seven    7.0
dtype: float64

In [210]:
s.map(t)

a    6.0
b    7.0
c    6.0
d    7.0
e    6.0
dtype: float64

In [212]:
# reindexing and altering labels
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s.reindex(["e", "b", "f", "d"])

e    0.683025
b    1.557894
f         NaN
d   -1.247390
dtype: float64

In [213]:
df.reindex(index=["c", "f", "b"], columns=["three", "two", "one"])

three       two       one
c -2.114859 -2.195142  0.762834
f       NaN       NaN       NaN
b  1.419732 -0.236325  1.726030

In [216]:
rs = s.reindex(df.index)
rs

a    0.635430
b    1.557894
c   -1.328330
d   -1.247390
dtype: float64

In [218]:
rs.index is df.index

True

In [219]:
df.reindex(["c", "f", "b"], axis="index")

one       two     three
c  0.762834 -2.195142 -2.114859
f       NaN       NaN       NaN
b  1.726030 -0.236325  1.419732

In [222]:
df2 = df.loc[:,['one','two']]

In [223]:
df.reindex_like(df2)

one       two
a -0.651103  0.104644
b  1.726030 -0.236325
c  0.762834 -2.195142
d       NaN  0.689498

In [224]:
# Aliging objects with each other with align
# align() join='outer'/'left'/'right'/'inner'
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s1 = s[:4]
s2 = s[1:]
s1.align(s2)

(a    0.039783
 b   -0.550302
 c    0.556081
 d   -0.660941
 e         NaN
 dtype: float64,
 a         NaN
 b   -0.550302
 c    0.556081
 d   -0.660941
 e   -0.443868
 dtype: float64)

In [225]:
s1.align(s2, join="inner")

(b   -0.550302
 c    0.556081
 d   -0.660941
 dtype: float64,
 b   -0.550302
 c    0.556081
 d   -0.660941
 dtype: float64)

In [226]:
 s1.align(s2, join="left")

(a    0.039783
 b   -0.550302
 c    0.556081
 d   -0.660941
 dtype: float64,
 a         NaN
 b   -0.550302
 c    0.556081
 d   -0.660941
 dtype: float64)

In [227]:
df.align(df2, join="inner")

(        one       two
 a -0.651103  0.104644
 b  1.726030 -0.236325
 c  0.762834 -2.195142
 d       NaN  0.689498,
         one       two
 a -0.651103  0.104644
 b  1.726030 -0.236325
 c  0.762834 -2.195142
 d       NaN  0.689498)

In [228]:
df.align(df2, join="inner", axis=0)

(        one       two     three
 a -0.651103  0.104644       NaN
 b  1.726030 -0.236325  1.419732
 c  0.762834 -2.195142 -2.114859
 d       NaN  0.689498  1.016124,
         one       two
 a -0.651103  0.104644
 b  1.726030 -0.236325
 c  0.762834 -2.195142
 d       NaN  0.689498)

In [229]:
df.align(df2.iloc[0], axis=1)

(        one     three       two
 a -0.651103       NaN  0.104644
 b  1.726030  1.419732 -0.236325
 c  0.762834 -2.114859 -2.195142
 d       NaN  1.016124  0.689498,
 one     -0.651103
 three         NaN
 two      0.104644
 Name: a, dtype: float64)

In [230]:
rng = pd.date_range("1/3/2000", periods=8)
ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts[[0, 3, 6]]
ts2.reindex(ts.index)

2000-01-03    2.202615
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    0.101821
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -2.032845
2000-01-10         NaN
Freq: D, dtype: float64

In [231]:
# These methods require that the indexes are ordered increasing or decreasing.
ts2.reindex(ts.index,method='ffill')

2000-01-03    2.202615
2000-01-04    2.202615
2000-01-05    2.202615
2000-01-06    0.101821
2000-01-07    0.101821
2000-01-08    0.101821
2000-01-09   -2.032845
2000-01-10   -2.032845
Freq: D, dtype: float64

In [233]:
ts2.reindex(ts.index,method='bfill')

2000-01-03    2.202615
2000-01-04    0.101821
2000-01-05    0.101821
2000-01-06    0.101821
2000-01-07   -2.032845
2000-01-08   -2.032845
2000-01-09   -2.032845
2000-01-10         NaN
Freq: D, dtype: float64

In [234]:
ts2.reindex(ts.index,method='nearest')

2000-01-03    2.202615
2000-01-04    2.202615
2000-01-05    0.101821
2000-01-06    0.101821
2000-01-07    0.101821
2000-01-08   -2.032845
2000-01-09   -2.032845
2000-01-10   -2.032845
Freq: D, dtype: float64

In [235]:
# reindex() will raise a ValueError if the index is not monotonically increasing or decreasing. fillna() and interpolate() will not perform any checks on the order of the index.
ts2.reindex(ts.index).fillna(method='ffill')

2000-01-03    2.202615
2000-01-04    2.202615
2000-01-05    2.202615
2000-01-06    0.101821
2000-01-07    0.101821
2000-01-08    0.101821
2000-01-09   -2.032845
2000-01-10   -2.032845
Freq: D, dtype: float64

In [236]:
# Dropping labels from an axis
df.drop(['a','d'],axis=0)

one       two     three
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859

In [237]:
df.drop(["one"], axis=1)

two     three
a  0.104644       NaN
b -0.236325  1.419732
c -2.195142 -2.114859
d  0.689498  1.016124

In [239]:
df.reindex(df.index.difference(["a", "d"]))

one       two     three
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859

In [240]:
# Renaming / mapping labels
# rename()
s

a      six
b    seven
c      six
d    seven
e      six
dtype: object

In [241]:
s.rename(str.upper)

A      six
B    seven
C      six
D    seven
E      six
dtype: object

In [242]:
 df.rename(
     columns={"one": "foo", "two": "bar"},
     index={"a": "apple", "b": "banana", "d": "durian"},
 )

foo       bar     three
apple  -0.651103  0.104644       NaN
banana  1.726030 -0.236325  1.419732
c       0.762834 -2.195142 -2.114859
durian       NaN  0.689498  1.016124

In [243]:
df.rename({"one": "foo", "two": "bar"}, axis="columns")

foo       bar     three
a -0.651103  0.104644       NaN
b  1.726030 -0.236325  1.419732
c  0.762834 -2.195142 -2.114859
d       NaN  0.689498  1.016124

In [244]:
# Pass inplace=True to rename the data in place
s.rename('scalar-name')

a      six
b    seven
c      six
d    seven
e      six
Name: scalar-name, dtype: object

In [245]:
df = pd.DataFrame(
     {"x": [1, 2, 3, 4, 5, 6], "y": [10, 20, 30, 40, 50, 60]},
     index=pd.MultiIndex.from_product(
         [["a", "b", "c"], [1, 2]], names=["let", "num"]
     ),
 )
df

x   y
let num       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [246]:
df.rename_axis(index={'let':'abc'})

x   y
abc num       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [247]:
df.rename_axis(index=str.upper)

x   y
LET NUM       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [249]:
# iteration
df = pd.DataFrame(
     {"col1": np.random.randn(3), "col2": np.random.randn(3)}, index=["a", "b", "c"]
 )
for i in df:
    print(i) # column labels
for i in s:
    print(i) # value

col1
col2
six
seven
six
seven
six


In [251]:
# iterrows(): Iterate over the rows of a DataFrame as (index, Series) pairs. This converts the rows to Series objects, which can change the dtypes and has some performance implications.
# itertuples(): Iterate over the rows of a DataFrame as namedtuples of the values. This is a lot faster than iterrows(), and is in most cases preferable to use to iterate over the values of a DataFrame.
# You should never modify something you are iterating over. This is not guaranteed to work in all cases. Depending on the data types, the iterator returns a copy and not a view, and writing to it will have no effect!
df = pd.DataFrame({"a": [1, 2, 3], "b": ["a", "b", "c"]})
for x in df.itertuples():
    print(x)

Pandas(Index=0, a=1, b='a')
Pandas(Index=1, a=2, b='b')
Pandas(Index=2, a=3, b='c')


In [253]:
# items
for label,ser in df.items():
    print(label)
    print(ser)

a
0    1
1    2
2    3
Name: a, dtype: int64
b
0    a
1    b
2    c
Name: b, dtype: object


In [254]:
# iterrows
for row_index,row in df.iterrows():
    print(row_index,row,sep='\n')

0
a    1
b    a
Name: 0, dtype: object
1
a    2
b    b
Name: 1, dtype: object
2
a    3
b    c
Name: 2, dtype: object


In [256]:
df_orig = pd.DataFrame([[1, 1.5]], columns=["int", "float"])
df_orig.dtypes

int        int64
float    float64
dtype: object

In [257]:
row = next(df_orig.iterrows())[1]
row

int      1.0
float    1.5
Name: 0, dtype: float64

In [260]:
df2 = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
df2.T

0  1  2
x  1  2  3
y  4  5  6

In [261]:
df2_t = pd.DataFrame({idx: values for idx, values in df2.iterrows()})
df2_t

0  1  2
x  1  2  3
y  4  5  6

In [262]:
# itertuples() preserves the data type of the values and is generally faster as iterrows().
for row in df.itertuples():
     print(row)

Pandas(Index=0, a=1, b='a')
Pandas(Index=1, a=2, b='b')
Pandas(Index=2, a=3, b='c')


In [266]:
# .dt accessor
# datetime
s = pd.Series(pd.date_range('20210101 09:11:10',periods=4))
s

0   2021-01-01 09:11:10
1   2021-01-02 09:11:10
2   2021-01-03 09:11:10
3   2021-01-04 09:11:10
dtype: datetime64[ns]

In [267]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int64

In [268]:
s.dt.second

0    10
1    10
2    10
3    10
dtype: int64

In [269]:
s[s.dt.day==2]

1   2021-01-02 09:11:10
dtype: datetime64[ns]

In [271]:
stz = s.dt.tz_localize('US/Eastern')
stz

0   2021-01-01 09:11:10-05:00
1   2021-01-02 09:11:10-05:00
2   2021-01-03 09:11:10-05:00
3   2021-01-04 09:11:10-05:00
dtype: datetime64[ns, US/Eastern]

In [272]:
stz.dt.tz

<DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD>

In [273]:
s.dt.tz_localize("UTC").dt.tz_convert('US/Eastern')

0   2021-01-01 04:11:10-05:00
1   2021-01-02 04:11:10-05:00
2   2021-01-03 04:11:10-05:00
3   2021-01-04 04:11:10-05:00
dtype: datetime64[ns, US/Eastern]

In [274]:
s = pd.Series(pd.date_range("20130101", periods=4))
s.dt.strftime('%Y/%m/%d %H:%M:%S')

0    2013/01/01 00:00:00
1    2013/01/02 00:00:00
2    2013/01/03 00:00:00
3    2013/01/04 00:00:00
dtype: object

In [276]:
s = pd.Series(pd.timedelta_range('1 day 00:00:05',periods=4,freq='s'))
s

0   1 days 00:00:05
1   1 days 00:00:06
2   1 days 00:00:07
3   1 days 00:00:08
dtype: timedelta64[ns]

In [278]:
print(s.dt.days,s.dt.seconds,s.dt.components,sep='\n')

0    1
1    1
2    1
3    1
dtype: int64
0    5
1    6
2    7
3    8
dtype: int64
   days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     1      0        0        5             0             0            0
1     1      0        0        6             0             0            0
2     1      0        0        7             0             0            0
3     1      0        0        8             0             0            0


In [279]:
# Vectorized string methods
s = pd.Series(
     ["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"], dtype="string"
 )

In [281]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5    <NA>
6    caba
7     dog
8     cat
dtype: string

In [282]:
# sorting
# by index
df = pd.DataFrame(
     {
         "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
         "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
         "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
     }
 )
unsorted_df = df.reindex(index=list('adcb'),columns=['three','two','one'])

In [283]:
unsorted_df.sort_index()

three       two       one
a       NaN  2.461281  1.656298
b -0.963865 -1.819268 -1.239013
c -1.728466 -1.357593  0.884406
d  0.776300  0.481156       NaN

In [284]:
unsorted_df.sort_index(ascending=False)

three       two       one
d  0.776300  0.481156       NaN
c -1.728466 -1.357593  0.884406
b -0.963865 -1.819268 -1.239013
a       NaN  2.461281  1.656298

In [285]:
unsorted_df.sort_index(axis=1)

one     three       two
a  1.656298       NaN  2.461281
d       NaN  0.776300  0.481156
c  0.884406 -1.728466 -1.357593
b -1.239013 -0.963865 -1.819268

In [287]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
     list("ab")
 )
s1

c
a b   
B 1  2
a 2  3
C 3  4

In [288]:
s1.sort_index(level='a')

c
a b   
B 1  2
C 3  4
a 2  3

In [289]:
s1.sort_index(level='a',key=lambda idx:idx.str.lower())

c
a b   
a 2  3
B 1  2
C 3  4

In [290]:
# by values
df1 = pd.DataFrame(
     {"one": [2, 1, 1, 1], "two": [1, 3, 2, 4], "three": [5, 4, 3, 2]}
 )
df1

one  two  three
0    2    1      5
1    1    3      4
2    1    2      3
3    1    4      2

In [291]:
df1.sort_values(by="two")

one  two  three
0    2    1      5
2    1    2      3
1    1    3      4
3    1    4      2

In [292]:
df1[["one", "two", "three"]].sort_values(by=["one", "two"])

one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

In [293]:
s[2] = np.nan
s.sort_values()

0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
2    <NA>
5    <NA>
dtype: string

In [294]:
s.sort_values(na_position='first')

2    <NA>
5    <NA>
0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
dtype: string

In [296]:
s1 = pd.Series(["B", "a", "C"])
s1.sort_values()

0    B
2    C
1    a
dtype: object

In [297]:
s1.sort_values(key=lambda x:x.str.lower())

1    a
0    B
2    C
dtype: object

In [298]:
# by indexes and values
idx = pd.MultiIndex.from_tuples(
     [("a", 1), ("a", 2), ("a", 2), ("b", 2), ("b", 1), ("b", 1)]
 )
idx.names = ["first", "second"]
df_multi = pd.DataFrame({"A": np.arange(6, 0, -1)}, index=idx)
df_multi

A
first second   
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

In [299]:
df_multi.sort_values(by=['second','A'])

A
first second   
b     1       1
      1       2
a     1       6
b     2       3
a     2       4
      2       5

In [300]:
# searchsorted
ser = pd.Series([1,2,3])
ser.searchsorted([0,3])

array([0, 2])

In [301]:
ser.searchsorted([0,4])

array([0, 3])

In [302]:
ser.searchsorted([1, 3], side="right")

array([1, 3])

In [303]:
ser.searchsorted([1, 3], side="left")

array([0, 2])

In [305]:
ser = pd.Series([3, 1, 2])
ser.searchsorted([0, 3], sorter=np.argsort(ser))

array([0, 2])

In [306]:
# smallest/largest values
s = pd.Series(np.random.permutation(10))
s

0    8
1    7
2    3
3    5
4    1
5    0
6    9
7    4
8    6
9    2
dtype: int64

In [307]:
s.sort_values()

5    0
4    1
9    2
2    3
7    4
3    5
8    6
1    7
0    8
6    9
dtype: int64

In [308]:
s.nsmallest(3)

5    0
4    1
9    2
dtype: int64

In [309]:
s.nlargest(3)

6    9
0    8
1    7
dtype: int64

In [311]:
 df = pd.DataFrame(
     {
         "a": [-2, -1, 1, 10, 8, 11, -1],
         "b": list("abdceff"),
         "c": [1.0, 2.0, 4.0, 3.2, np.nan, 3.0, 4.0],
     }
 )
df

a  b    c
0  -2  a  1.0
1  -1  b  2.0
2   1  d  4.0
3  10  c  3.2
4   8  e  NaN
5  11  f  3.0
6  -1  f  4.0

In [312]:
df.nlargest(3,'a')

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN

In [313]:
df.nlargest(5,['a','c'])

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN
2   1  d  4.0
6  -1  f  4.0

In [314]:
print(df.nsmallest(3,'a'),df.nsmallest(5,['a','c']),sep='\n')

   a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0
   a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0
2  1  d  4.0
4  8  e  NaN


In [316]:
# sorting by a multiIndex column
df1.columns = pd.MultiIndex.from_tuples([("a", "one"), ("a", "two"), ("b", "three")])
df1

a         b
  one two three
0   2   1     5
1   1   3     4
2   1   2     3
3   1   4     2

In [317]:
df1.sort_values(by=('a','two'))

a         b
  one two three
0   2   1     5
2   1   2     3
1   1   3     4
3   1   4     2

In [318]:
# copying
# alter a dataframe in-place
# Inserting, deleting, or modifying a column.
# Assigning to the index or columns attributes.
# For homogeneous data, directly modifying the values via the values attribute or advanced indexing

In [324]:
# dtype
dtype_summary = pd.DataFrame(
{'Kind of Data': ['tz-aware datetime', 'Categorical', 'period (time spans)', 'sparse', 'intervals', 'nullable integer', 'Strings', 'Boolean (with NA)'], 'Data Type': ['DatetimeTZDtype', 'CategoricalDtype', 'PeriodDtype', 'SparseDtype', 'IntervalDtype', 'Int64Dtype, …', 'StringDtype', 'BooleanDtype'], 'Scalar': ['Timestamp', '(none)', 'Period', '(none)', 'Interval', '(none)', 'str', 'bool'], 'Array': ['arrays.DatetimeArray', 'Categorical', 'arrays.PeriodArray', 'arrays.SparseArray', 'arrays.IntervalArray', 'arrays.IntegerArray', 'arrays.StringArray', 'arrays.BooleanArray'], 'String Aliases': ["'datetime64[ns, <tz>]'", "'category'", "'period[<freq>]', 'Period[<freq>]'", "'Sparse', 'Sparse[int]', 'Sparse[float]'", "'interval', 'Interval', 'Interval[<numpy_dtype>]', 'Interval[datetime64[ns, <tz>]]', 'Interval[timedelta64[<freq>]]'", "'Int8', 'Int16', 'Int32', 'Int64', 'UInt8', 'UInt16', 'UInt32', 'UInt64'", "'string'", "'boolean'"], 'Documentation': ['Time zone handling', 'Categorical data', 'Time span representation', 'Sparse data structures', 'IntervalIndex', 'Nullable integer data type', 'Working with text data','Boolean data with missing values']}
)
dtype_summary

Kind of Data  ...                     Documentation
0    tz-aware datetime  ...                Time zone handling
1          Categorical  ...                  Categorical data
2  period (time spans)  ...          Time span representation
3               sparse  ...            Sparse data structures
4            intervals  ...                     IntervalIndex
5     nullable integer  ...        Nullable integer data type
6              Strings  ...            Working with text data
7    Boolean (with NA)  ...  Boolean data with missing values

[8 rows x 6 columns]

[dtype](https://pandas.pydata.org/docs/user_guide/basics.html#dtypes)

In [325]:
dft = pd.DataFrame(
     {
         "A": np.random.rand(3),
         "B": 1,
         "C": "foo",
         "D": pd.Timestamp("20010102"),
        "E": pd.Series([1.0] * 3).astype("float32"),
         "F": False,
         "G": pd.Series([1] * 3, dtype="int8"),
    }
 )
dft

A  B    C          D    E      F  G
0  0.355239  1  foo 2001-01-02  1.0  False  1
1  0.940691  1  foo 2001-01-02  1.0  False  1
2  0.751799  1  foo 2001-01-02  1.0  False  1

In [327]:
dft.dtypes

A           float64
B             int64
C            object
D    datetime64[ns]
E           float32
F              bool
G              int8
dtype: object

In [329]:
dft['A'].dtype

dtype('float64')

In [330]:
pd.Series([1, 2, 3, 4, 5, 6.0])

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [331]:
pd.Series([1, 2, 3, 6.0, "foo"])

0      1
1      2
2      3
3    6.0
4    foo
dtype: object

In [332]:
dft.dtypes.value_counts()

datetime64[ns]    1
object            1
int8              1
float64           1
int64             1
bool              1
float32           1
dtype: int64

In [333]:
df1 = pd.DataFrame(np.random.randn(8, 1), columns=["A"], dtype="float32")
df1

A
0 -0.706829
1  0.837600
2  0.943482
3  0.238653
4  0.035899
5 -1.096693
6 -0.245622
7 -0.202428

In [334]:
df1.dtypes

A    float32
dtype: object

In [335]:
# By default integer types are int64 and float types are float64, regardless of platform (32-bit or 64-bit)
pd.DataFrame([1, 2], columns=["a"]).dtypes

a    int64
dtype: object

In [339]:
# upcasting
df2 = pd.DataFrame(
    {
         "A": pd.Series(np.random.randn(8), dtype="float16"),
         "B": pd.Series(np.random.randn(8)),
         "C": pd.Series(np.array(np.random.randn(8), dtype="uint8")),
     }
 )
df3 = df1.reindex_like(df2).fillna(value=0.0) + df2
df3

A         B      C
0  0.584187 -1.689272    0.0
1  0.486037 -1.183743    0.0
2  1.821412  0.180720    0.0
3 -1.612910  0.703575    1.0
4  0.078135 -0.576084    0.0
5 -1.022779  1.605162    0.0
6  0.407698 -1.400359    0.0
7  0.321986  0.395013  255.0

In [340]:
df3.dtypes

A    float32
B    float64
C    float64
dtype: object

In [341]:
df3.to_numpy().dtype

dtype('float64')

In [343]:
# astype
df3.astype('float32').dtypes

A    float32
B    float32
C    float32
dtype: object

In [344]:
dft = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
dft[["a", "b"]] = dft[["a", "b"]].astype(np.uint8)
dft.dtypes

a    uint8
b    uint8
c    int64
dtype: object

In [345]:
dft1 = pd.DataFrame({"a": [1, 0, 1], "b": [4, 5, 6], "c": [7, 8, 9]})
dft1 = dft1.astype({"a": np.bool_, "c": np.float64})
dft1

a  b    c
0   True  4  7.0
1  False  5  8.0
2   True  6  9.0

In [346]:
dft1.dtypes

a       bool
b      int64
c    float64
dtype: object

In [348]:
# object conversion
import datetime
df = pd.DataFrame(
    [
         [1, 2],
         ["a", "b"],
         [datetime.datetime(2016, 3, 2), datetime.datetime(2016, 3, 2)],
    ]
)
df = df.T
df

0  1          2
0  1  a 2016-03-02
1  2  b 2016-03-02

In [349]:
df.dtypes

0            object
1            object
2    datetime64[ns]
dtype: object

In [350]:
 df.infer_objects().dtypes

0             int64
1            object
2    datetime64[ns]
dtype: object

In [352]:
m = ["1.1", 2, 3]
pd.to_numeric(m)    

array([1.1, 2. , 3. ])

In [353]:
m = ["2016-07-09", datetime.datetime(2016, 3, 2)]
pd.to_datetime(m)

DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [355]:
m = ["5us", pd.Timedelta("1day")]
pd.to_timedelta(m)

TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)

In [356]:
# By default, errors='raise', meaning that any errors encountered will be raised during the conversion process. 
# if errors='coerce', these errors will be ignored and pandas will convert problematic elements to pd.NaT (for datetime and timedelta) or np.nan (for numeric).
m = ["apple", datetime.datetime(2016, 3, 2)]
pd.to_datetime(m, errors="coerce")

DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [357]:
m = ["apple", 2, 3]
pd.to_numeric(m, errors="coerce")

array([nan,  2.,  3.])

In [358]:
m = ["apple", pd.Timedelta("1day")]
pd.to_timedelta(m, errors="coerce")

TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)

In [359]:
# errors='ignore', which will simply return the passed in data if it encounters any errors with the conversion to a desired data type
m = ["apple", datetime.datetime(2016, 3, 2)]
pd.to_datetime(m, errors="ignore")

Index(['apple', 2016-03-02 00:00:00], dtype='object')

In [360]:
#  to_numeric() provides another argument downcast, which gives the option of downcasting the newly (or already) numeric data to a smaller dtype
m = [1,2,3]
pd.to_numeric(m,downcast='integer')

array([1, 2, 3], dtype=int8)

In [361]:
pd.to_numeric(m,downcast='signed')

array([1, 2, 3], dtype=int8)

In [362]:
pd.to_numeric(m,downcast='unsigned')

array([1, 2, 3], dtype=uint8)

In [363]:
pd.to_numeric(m,downcast='float')

array([1., 2., 3.], dtype=float32)

In [368]:
df = pd.DataFrame([["1.1", 2, 3]] * 2)
df.apply(pd.to_numeric,downcast='float')

0    1    2
0  1.1  2.0  3.0
1  1.1  2.0  3.0

In [369]:
df.dtypes

0    object
1     int64
2     int64
dtype: object

In [370]:
# gotchas
dfi = df3.astype('int32')

In [371]:
dfi['E'] = 1

In [372]:
dfi

A  B    C  E
0  0 -1    0  1
1  0 -1    0  1
2  1  0    0  1
3 -1  0    1  1
4  0  0    0  1
5 -1  1    0  1
6  0 -1    0  1
7  0  0  255  1

In [374]:
dfi.dtypes

A    int32
B    int32
C    int32
E    int64
dtype: object

In [375]:
casted = dfi[dfi>0]
casted

A    B      C  E
0  NaN  NaN    NaN  1
1  NaN  NaN    NaN  1
2  1.0  NaN    NaN  1
3  NaN  NaN    1.0  1
4  NaN  NaN    NaN  1
5  NaN  1.0    NaN  1
6  NaN  NaN    NaN  1
7  NaN  NaN  255.0  1

In [376]:
casted.dtypes

A    float64
B    float64
C    float64
E      int64
dtype: object

In [377]:
# Selecting columns based on dtype
# select_dtype()
df = pd.DataFrame(
     {
         "string": list("abc"),
         "int64": list(range(1, 4)),
         "uint8": np.arange(3, 6).astype("u1"),
         "float64": np.arange(4.0, 7.0),
         "bool1": [True, False, True],
         "bool2": [False, True, False],
         "dates": pd.date_range("now", periods=3),
         "category": pd.Series(list("ABC")).astype("category"),
     }
 )
df["tdeltas"] = df.dates.diff()
df["uint64"] = np.arange(3, 6).astype("u8")
df["other_dates"] = pd.date_range("20130101", periods=3)
df["tz_aware_dates"] = pd.date_range("20130101", periods=3, tz="US/Eastern")
df

string  int64  uint8  ...  uint64  other_dates            tz_aware_dates
0      a      1      3  ...       3   2013-01-01 2013-01-01 00:00:00-05:00
1      b      2      4  ...       4   2013-01-02 2013-01-02 00:00:00-05:00
2      c      3      5  ...       5   2013-01-03 2013-01-03 00:00:00-05:00

[3 rows x 12 columns]

In [378]:
df.dtypes

string                                object
int64                                  int64
uint8                                  uint8
float64                              float64
bool1                                   bool
bool2                                   bool
dates                         datetime64[ns]
category                            category
tdeltas                      timedelta64[ns]
uint64                                uint64
other_dates                   datetime64[ns]
tz_aware_dates    datetime64[ns, US/Eastern]
dtype: object

In [379]:
# include exclude
df.select_dtypes(include=[bool])

bool1  bool2
0   True  False
1  False   True
2   True  False

In [380]:
df.select_dtypes(include=['bool'])

bool1  bool2
0   True  False
1  False   True
2   True  False

In [381]:
# string object
df.select_dtypes(include=['object'])

string
0      a
1      b
2      c

In [382]:
def subdtypes(dtype):
    subs = dtype.__subclasses__()
    if not subs:
        return dtype
    return [dtype, [subdtypes(dt) for dt in subs]]

In [383]:
subdtypes(np.generic)

[numpy.generic,
 [[numpy.number,
   [[numpy.integer,
     [[numpy.signedinteger,
       [numpy.int8,
        numpy.int16,
        numpy.int32,
        numpy.int64,
        numpy.longlong,
        numpy.timedelta64]],
      [numpy.unsignedinteger,
       [numpy.uint8,
        numpy.uint16,
        numpy.uint32,
        numpy.uint64,
        numpy.ulonglong]]]],
    [numpy.inexact,
     [[numpy.floating,
       [numpy.float16, numpy.float32, numpy.float64, numpy.float128]],
      [numpy.complexfloating,
       [numpy.complex64, numpy.complex128, numpy.complex256]]]]]],
  [numpy.flexible,
   [[numpy.character, [numpy.bytes_, numpy.str_]],
    [numpy.void, [numpy.record]]]],
  numpy.bool_,
  numpy.datetime64,
  numpy.object_]]