+ 数字的四舍五入

In [2]:
round(1.23,1),round(-1.27,1),round(1.25361,3)

(1.2, -1.3, 1.254)

`round` 当一个值在两个边界中间时，返回离它最近的偶数

In [3]:
round(1.5),round(2.5)

(2, 2)

In [4]:
a = 1627731
round(a,-1),round(a,-2),round(a,-3)

(1627730, 1627700, 1628000)

+ 精确的浮点数运算

In [6]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
a + b

Decimal('6.3')

In [7]:
a,b = 4.2,2.1
a + b

6.300000000000001

In [8]:
from decimal import localcontext
a,b = Decimal('1.3'),Decimal('1.7')
a/b

Decimal('0.7647058823529411764705882353')

In [10]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.765


In [11]:
with localcontext() as ctx:
    ctx.prec = 50
    print(a/b)

0.76470588235294117647058823529411764705882352941176


In [13]:
nums = [1.23e+18, 1, -1.23e+18]
import math
sum(nums),math.fsum(nums)

(0.0, 1.0)

+ 数字的格式化输出

In [14]:
x = 1234.56789
format(x,'0.2f'),format(x,'>10.1f'),format(x,'<10.1f'),format(x,'^10.1f'),format(x,','),format(x,'10,.1f')

('1234.57',
 '    1234.6',
 '1234.6    ',
 '  1234.6  ',
 '1,234.56789',
 '   1,234.6')

In [15]:
format(x,'e'),format(x,'0.2E')

('1.234568e+03', '1.23E+03')

`'[<>^]?width[,]?(.digits)?'` ?代表可选部分

`format` 指定位数后使用`round()`函数进行四舍五入后返回

+ 二八十六进制整数

`bin()`  
`oct()`  
`hex()`

In [16]:
x = 1234
bin(x),oct(x),hex(x)

('0b10011010010', '0o2322', '0x4d2')

In [17]:
format(x,'b'),format(x,'o'),format(x,'x')

('10011010010', '2322', '4d2')

+ 复数的数学运算

In [18]:
a = complex(2,4)
b = 3-5j
a,b

((2+4j), (3-5j))

In [19]:
a.real,a.imag,a.conjugate()

(2.0, 4.0, (2-4j))

In [20]:
a+b,a*b,a/b,abs(a)

((5-1j), (26+2j), (-0.4117647058823529+0.6470588235294118j), 4.47213595499958)

In [22]:
import cmath
cmath.sin(a),cmath.cos(a),cmath.exp(a),cmath.sqrt(-1)

((24.83130584894638-11.356612711218174j),
 (-11.36423470640106-24.814651485634187j),
 (-4.829809383269385-5.5920560936409816j),
 1j)

+ 无穷大和nan

In [23]:
a,b,c = float('inf'),float('-inf'),float('nan')
a,b,c

(inf, -inf, nan)

In [24]:
math.isinf(a),math.isnan(c)

(True, True)

+ 分数运算

In [26]:
from fractions import Fraction
a,b = Fraction(5,4),Fraction(7,16)
a+b,a*b

(Fraction(27, 16), Fraction(35, 64))

In [27]:
c=a*b
c.numerator,c.denominator

(35, 64)

In [28]:
float(c)

0.546875

In [29]:
c.limit_denominator(8)

Fraction(4, 7)

In [31]:
x = 3.75
y = Fraction(*x.as_integer_ratio())
x.as_integer_ratio(),y

((15, 4), Fraction(15, 4))

In [32]:
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
ax*2,ax+10,ax+ay,ax*ay

(array([2, 4, 6, 8]),
 array([11, 12, 13, 14]),
 array([ 6,  8, 10, 12]),
 array([ 5, 12, 21, 32]))

In [33]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

+ 矩阵和线性代数运算

In [35]:
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [36]:
m.T,m.I

(matrix([[ 1,  0,  7],
         [-2,  4,  8],
         [ 3,  5, -9]]),
 matrix([[ 0.33043478, -0.02608696,  0.09565217],
         [-0.15217391,  0.13043478,  0.02173913],
         [ 0.12173913,  0.09565217, -0.0173913 ]]))

In [37]:
v = np.matrix([[2],[3],[4]])
m*v

matrix([[ 8],
        [32],
        [ 2]])

In [39]:
import numpy.linalg
numpy.linalg.det(m)

-229.99999999999983

In [40]:
numpy.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [41]:
x = numpy.linalg.solve(m,v)
x,m*x,v

(matrix([[0.96521739],
         [0.17391304],
         [0.46086957]]),
 matrix([[2.],
         [3.],
         [4.]]),
 matrix([[2],
         [3],
         [4]]))

+ 随机选择

In [42]:
import random
values = [1,2,3,4,5,6]
random.choice(values),random.choice(values),random.choice(values),random.choice(values),random.choice(values)

(2, 6, 4, 4, 1)

In [44]:
random.sample(values,1),random.sample(values,2),random.sample(values,3),random.sample(values,4),random.sample(values,5)

([1], [3, 4], [6, 5, 2], [3, 4, 2, 6], [5, 4, 6, 3, 2])

In [46]:
random.shuffle(values)
values

[1, 5, 2, 3, 6, 4]

In [47]:
random.randint(0,10)

7

In [48]:
random.random()

0.09952122601852131

In [52]:
random.getrandbits(1000)

2330191825908414359731058177250367513359221766007894310196640648786935488876957405843728994496612312720372511184684942903394859102620185814061574199541211099081840518039097082188629795252963070634040309319684429514228331469143777977254944287740922386406034095283886617484311552818399124887356814228733

+ 基本的日期和时间转换

In [56]:
from datetime import timedelta,datetime
a = timedelta(days = 2,hours=6)
b = timedelta(hours=4.5)
c = a+b
c.days,c.seconds,c.seconds/3600,c.total_seconds()/3600

(2, 37800, 10.5, 58.5)

In [57]:
from dateutil.relativedelta import relativedelta
a = datetime(2021,9,23)
a + relativedelta(months=+1)

datetime.datetime(2021, 10, 23, 0, 0)

In [58]:

from datetime import datetime, date, timedelta
import calendar
def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date, end_date)

+ Python的迭代器协议需要 `__iter__()` 方法返回一个实现了`__next__()` 方法的迭代器对象

In [60]:
class Node:
    def __init__(self, value):
        self._value = value
        self._children = []

    def __repr__(self):
        return 'Node({!r})'.format(self._value)

    def add_child(self, node):
        self._children.append(node)

    def __iter__(self):
        return iter(self._children)

    def depth_first(self):
        yield self
        for c in self:
            yield from c.depth_first()
root = Node(0)
child1 = Node(1)
child2 = Node(2)
root.add_child(child1)
root.add_child(child2)
child1.add_child(Node(3))
child1.add_child(Node(4))
child2.add_child(Node(5))
for ch in root.depth_first():
    print(ch)

Node(0)
Node(1)
Node(3)
Node(4)
Node(2)
Node(5)


+ 带有外部状态的生成器  
一个函数中需要有一个 `yield` 语句即可将其转换为一个生成器。

In [61]:
from collections import deque

class linehistory:
    def __init__(self, lines, histlen=3):
        self.lines = lines
        self.history = deque(maxlen=histlen)

    def __iter__(self):
        for lineno, line in enumerate(self.lines, 1):
            self.history.append((lineno, line))
            yield line  # 生成器协议

    def clear(self):
        self.history.clear()

+ 迭代器切片  
`itertools.islice`

In [63]:
def count(n):
    while True:         
        yield n
        n += 1
import itertools
c = count(0)
for x in itertools.islice(c, 10, 20):
    print(x)

10
11
12
13
14
15
16
17
18
19


+ 跳过可迭代对象的开始部分  
`itertools.islice`  
`itertools.dropwhile`

In [70]:
from itertools import dropwhile
items = ['a', 'b', 'c', 1, 4, 10, 15,'e']
for x in dropwhile(lambda x:isinstance(x,str),items):
    print(x)
    print(not isinstance(x,str))

1
True
4
True
10
True
15
True
e
False


+ 排列组合的迭代  
排列：`itertools.permutations`  
组合：`itertools.combinations`

In [71]:
from itertools import permutations
items = ['a','b','c']
for p in permutations(items):
    print(p)

('a', 'b', 'c')
('a', 'c', 'b')
('b', 'a', 'c')
('b', 'c', 'a')
('c', 'a', 'b')
('c', 'b', 'a')


In [72]:
for p in permutations(items,2):
    print(p)

('a', 'b')
('a', 'c')
('b', 'a')
('b', 'c')
('c', 'a')
('c', 'b')


In [74]:
from itertools import combinations
for c in combinations(items,3):
    print(c)

('a', 'b', 'c')


In [75]:
for c in combinations(items,2):
    print(c)

('a', 'b')
('a', 'c')
('b', 'c')


In [76]:
from itertools import combinations_with_replacement
for c in combinations_with_replacement(items,3):
    print(c)

('a', 'a', 'a')
('a', 'a', 'b')
('a', 'a', 'c')
('a', 'b', 'b')
('a', 'b', 'c')
('a', 'c', 'c')
('b', 'b', 'b')
('b', 'b', 'c')
('b', 'c', 'c')
('c', 'c', 'c')


+ 序列上索引值迭代  
`enumerate`

+ 同时迭代多个序列  
`zip`  
`itertools.zip_longest`

In [80]:
dict(zip(range(10),range(10,0,-1)))

{0: 10, 1: 9, 2: 8, 3: 7, 4: 6, 5: 5, 6: 4, 7: 3, 8: 2, 9: 1}

In [81]:
from itertools import zip_longest
a = [1,2,3]
b = ['w', 'x', 'y', 'z']
list(zip(a,b)),list(zip_longest(a,b))

([(1, 'w'), (2, 'x'), (3, 'y')], [(1, 'w'), (2, 'x'), (3, 'y'), (None, 'z')])

+ 不同集合上元素的迭代  
`itertools.chain`

In [82]:
from itertools import chain
for x in chain(a,b):
    print(x)

1
2
3
w
x
y
z


In [86]:
import os
for root, dirs, files in os.walk("/Users/huzhenyu/Downloads/4月份", topdown=False):
    print(root,dirs,files,sep='\n')

/Users/huzhenyu/Downloads/4月份/changanoushangX7-2021
[]
['2021款长安睿行M80配置表（附指导价）(1).xlsx', '2021款长安睿行M80配置表（附指导价）(1)_new.xlsx', '2021款长安欧尚X7Geeker版配置表(1)(1)_new.xlsx', '2021款长安欧尚X7Geeker版配置表(1)(1).xlsx']
/Users/huzhenyu/Downloads/4月份/xinbaojunvalli-2021
[]
['新宝骏Valli产品参数配置表_new.xlsx', '新宝骏Valli产品参数配置表.xlsx']
/Users/huzhenyu/Downloads/4月份/jinlongkaige-2021
[]
['2021年厦门金龙轻客车型配置价格表_new.xlsx', '2021年厦门金龙轻客车型配置价格表.xlsx']
/Users/huzhenyu/Downloads/4月份/jianglingfutelingyu-2021
[]
['2021款江铃福特领裕配置表_new.xlsx', '2021款江铃福特领裕配置表.xlsx', '福特领裕6座车型配置表.xlsx', '福特领裕6座车型配置表_new.xlsx']
/Users/huzhenyu/Downloads/4月份/weiting-2021
[]
['2021-Vito_brochure.pdf']
/Users/huzhenyu/Downloads/4月份/dongfengfengguangS560-2021
[]
['2021款风光S560参数配置表(1)_new.xlsx', '2021款风光S560参数配置表(1).xlsx']
/Users/huzhenyu/Downloads/4月份/jilidihaos-2021
[]
['帝豪S车型参数配置表(1).xlsx', '帝豪S车型参数配置表(1)_new.xlsx']
/Users/huzhenyu/Downloads/4月份/tianjime7-2021
[]
['天际me7最新配置表_new.xlsx', '天际me7最新配置表.xlsx']
/Users/huzhenyu/Downloads/4月份/gaohe HiPhi X-20

In [88]:
import os
import fnmatch
import gzip
import bz2
import re

def gen_find(filepat, top):
    '''
    Find all filenames in a directory tree that match a shell wildcard pattern
    '''
    for path, dirlist, filelist in os.walk(top):
        for name in fnmatch.filter(filelist, filepat):
            yield os.path.join(path,name)

def gen_opener(filenames):
    '''
    Open a sequence of filenames one at a time producing a file object.
    The file is closed immediately when proceeding to the next iteration.
    '''
    for filename in filenames:
        if filename.endswith('.gz'):
            f = gzip.open(filename, 'rt')
        elif filename.endswith('.bz2'):
            f = bz2.open(filename, 'rt')
        else:
            f = open(filename, 'rt')
        yield f
        f.close()

def gen_concatenate(iterators):
    '''
    Chain a sequence of iterators together into a single sequence.
    '''
    for it in iterators:
        yield from it

def gen_grep(pattern, lines):
    '''
    Look for a regex pattern in a sequence of lines
    '''
    pat = re.compile(pattern)
    for line in lines:
        if pat.search(line):
            yield line
            
lognames = gen_find('access-log*', '.')
files = gen_opener(lognames)
lines = gen_concatenate(files)
pylines = gen_grep('(?i)python', lines)
for line in pylines:
    print(line)

+ 展开嵌套的序列

In [90]:
from collections import Iterable

def flatten(items, ignore_types=(str, bytes)):
    for x in items:
        if isinstance(x, Iterable) and not isinstance(x, ignore_types):
            yield from flatten(x)
        else:
            yield x

items = [1, 2, [3, 4, [5, 6], 7], 8]
# Produces 1 2 3 4 5 6 7 8
for x in flatten(items):
    print(x)

1
2
3
4
5
6
7
8


/var/folders/g6/h24w2cnn0bzbzz1dc4v4fplm0000gn/T/ipykernel_74780/3239541074.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable


+ 顺序迭代合并后的排序迭代对象  
`heapq.merge`

In [92]:
import heapq
a = [1,4,7,10]
b = [2,3,6,11]
for c in heapq.merge(a,b):
    print(c)

1
2
3
4
6
7
10
11


In [93]:
a = [1,4,7,10]
b = [2,3,11,6]
for c in heapq.merge(a,b):
    print(c)

1
2
3
4
7
10
11
6
